---
title: "People and their favourite animals"
execute: 
  echo: false
  message: false
  warning: false
bibliography: references.bib
---

```{r}
library(tidyverse)
```

```{r}
#| include: false
people = readr::read_csv("data/people.csv")
dim(people)
names(people)
# remove tbc rows:
people = people |>
  filter(name != "tbc") |>
  # Make animal names consistent, lowercase
  mutate(animal = tolower(animal))
dim(people)
animal_popularity = people |>
  count(animal, sort=TRUE) |>
  filter(n > 1)
```

See the most popular animals in @tbl-animal-popularity.

```{r}
#| label: tbl-animal-popularity
knitr::kable(animal_popularity, caption = "Most popular animals")
```

See a map of locations where people are from in @fig-people-map.

[@paulsen2024]

```{r}
#| label: fig-people-map-data
if (!file.exists("data/people_geo.gejson")) {
  if (!requireNamespace("tidygeocoder", quietly = TRUE)) install.packages("tidygeocoder")
  library(sf)
  people_geo = people |>
    tidygeocoder::geocode(address = from, method = 'osm', lat = latitude , long = longitude) |>
    # add random jitter to avoid overplotting
    mutate(latitude = latitude + rnorm(n(), 0, 1),
           longitude = longitude + rnorm(n(), 0, 1)) |>
    st_as_sf(coords = c("longitude", "latitude"), crs = 4326)
  people_geo
  sf::write_sf(people_geo, "data/people_geo.geojson", delete_dsn = TRUE)
} else {
  library(sf)
  people_geo = sf::read_sf("data/people_geo.geojson")
}
```

```{r}
#| label: fig-people-map
#| fig-cap: Map showing where people are from and their favourite animals
library(tmap)
tmap_mode("view")
tm_shape(people_geo) +
  tm_dots(size = 1, fill = "animal")
```

Here's an equation for calculating the number of animals in each category:

$$
N = \sum_{i=1}^{k} n_i
$$

```{r}
# Save updated csv file
people_updated = people_geo |>
  filter(!str_detect(username, "robin|juan")) |>
  st_drop_geometry() |>
  select(username)
people_updated$reviews = c(people_updated$username[-1], people_updated$username[1])
readr::write_csv(people_updated, "data/people_updated.csv")
```

# References
