---
title: "Prerequisites"
---

## Course Prerequisites

This course assumes working knowledge with R or Python for research. We assume that you are already comfortable with an integrated development environment (IDE), such as RStudio or VS Code. You must have a GitHub account and it will be beneficial to be familiar with the concepts of version control, although we will cover these in the course.

Familiarity with referencing software such as Zotero (recommended) and bibliography file formats such as BibTeX will be beneficial, but not essential.

## Software Prerequisites

You should bring a laptop with the following software installed and tested to check it works:

- Quarto (minimum version: 1.5.45)
- A tested R or Python installation or both (note: if you have Docker installed you should be able to run R and Python inside a devcontainer, works best with VS Code)
- RStudio or VS Code
  - If you will use VS Code for the course, you need the following extensions:
    - The R extension `reditorsupport.r` if using R
    - The Python extension `ms-python.python` if using Python
    - The quarto extention `quarto.quarto`
- Git, installed with one of the following packages:
  - GitHub Desktop (see [desktop.github.com](https://desktop.github.com/))
  - Git for the command line (see [git-scm.com](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git))
- The `gh` command-line tool (see [cli.github.com](https://cli.github.com/) for installation and set-up instructions)

## Recommended Online Courses

Students should take these short but very useful online courses to prepare:

- [Intro to GitHub](https://github.com/skills/introduction-to-github)
- [Communicate using Markdown](https://github.com/skills/communicate-using-markdown)
