---
format: gfm
---

# Quarto course website template

A template for course websites developed with [Quarto](https://quarto.org) and hosted on GitHub.

This is all configured so you only need to edit the source files in Quarto (.qmd). The website is generated and hosted automatically by GitHub.

Example website: https://pakillo.github.io/quarto-course-website-template (see also https://github.com/rstudio-conf-2022/teach-ds-course-website for a more developed example).


## Using this template

1. Click on green button "Use this template" -> "Create a new repository"

2. Choose a name for your repository

3. Important: check 'Include all branches' when creating the repository (because we will need the `gh-pages` branch to host the website).

4. Once your repo is created, remember to update the links to your GitHub repo in [_quarto.yml](_quarto.yml), replacing 'Pakillo' with your GitHub username.

To create an empty branch and take a look at the [Quarto documentation](https://quarto.org/docs/publishing/github-pages.html):

```bash
git checkout --orphan gh-pages
git reset --hard # make sure all changes are committed before running this!
git commit --allow-empty -m "Initialising gh-pages branch"
git push origin gh-pages
```

