---
title: "Tools and Skills for Reproducible Transport Research"
---

<!-- Course team (TBC):

Robin Lovelace, Rosa Felix, TBC -->

## Learning objectives

- Be able to share reproducible code for more scientific and transparent transport research
- To be confident reproducing your own work and that of others
- To become skilled at using Git and GitHub to manage versions of your code and collaborate with others
- To be able to write reproducible content that can be exported to a variety of formats with the Quarto system for scientific publishing
- To understand how Quarto extensions can be used as a basis for creating publication-ready papers
- To be aware of 'continuous integration' and 'GitHub Actions' and how they can be used to ensure reproducibility, share your work, and save time
- Understanding of best practices around code sharing and collaboration for reproducible research in transport planning

## Prerequisites

This course assumes working knowledge with R or Python for research.
We assume that you are already comfortable with an integrated development environment (IDE), such as RStudio or VS Code.
You must have a GitHub account and it will be beneficial to be familiar with the concepts of version control, although we will cover these in the course.

Familiarity with referencing software such as Zotero (recommended) and bibliography file formats such as BibTeX will be beneficial, but not essential.

## Software prerequisites

You should bring a laptop with the following software installed and tested to check it works:

- Quarto (minimum version: 1.5.45)
- R or Python or both
- RStudio (recommended for most people) or VS Code
  - If you will use VS Code for the course, you need the following extensions:
    - The R extension `reditorsupport.r` if using R
    - The Python extension `ms-python.python` if using Python
    - The quarto extention `quarto.quarto`
- Git, installed with one of the following packages:
  - GitHub Desktop (see [desktop.github.com](https://desktop.github.com/))
  - Git for the command line (see [git-scm.com](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git))
- The `gh` command-line tool (see [cli.github.com](https://cli.github.com/) for installation and set-up instructions)

## Day 1

- 09:30-10:00 Introduction
  - Welcome and introductions (participatory)
  - Definitions and motivations
  - Course structure and objectives 
- 10:00-11:00 Development environments, system commands, and version control
  - Introduction to RStudio and VS Code
  - Key features and extensions of VS Code
  - The system shell and basic commands
  - Introduction to Git and GitHub
  - The `gh` command-line tool
  - Practical: setting up your development environment and using the `gh` command-line tool
    - Worked example starting with:
      - `gh repo clone tdscience/course`
      - `cd course`
      - `gh issue list`
      - `gh issue create` 
- 11:00-11:15 Break
- 11:15-12:30 Sharing code and data
  - Navigating GitHub
  - Your profile and repositories
  - Creating and managing repositories
    - Cloning repositories
    - Making changes and committing
    - Pushing changes to GitHub
  - Collaboration with GitHub
    - Branches and pull requests
    - Merging changes
    - Resolving conflicts
  - Automated workflows with GitHub Actions
  - Best practices for collaboration, sharing code and data
  - Practical: creating a repository and making changes
- 12:30-13:30 Lunch
- 13:30-15:00 Reproducible papers and documentation with Quarto
    - Introduction to Quarto
    - Markdown, LaTeX, and file formats
    - Code chunks and settings
    - Publishing your work
    - Demonstration of reproducible papers
    - Practical: creating a minimal reproducible paper
- 15:00-15:15 Break
- 15:15-16:30 Cross-references and citations with Quarto
    - Cross-references
    - Citations
    - Bibliographies
    - Tables and figures
    - Practical: adding citations and references to your paper

## Day 2

- 09:30-10:30 Drafting a reproducible paper
  - Recap of Day 1
  - Topic selection
  - Individual work on paper drafts
- 10:30-10:45 Break
- 10:45-12:30 Generating reproducible publication-quality visualisations
  - An introduction to visualisation and web application development for transport planning
  - A deep dive into ggplot2
  - Practical: creating a visualisation for your paper
  <!-- - Interactive content for papers
  - Static vs dynamic web applications
  - Practical introduction to Shiny for R and Python
  - (Optional): Front-end development -->
- 12:30-13:30 Lunch
- 13:30-14:30 Editing other people's work
  - Reviewing and commenting on papers
  - Making changes and submitting Pull Requests
  - Controlled chaos: choose a paper and make some changes!
- 14:30-14:45 Break
- 14:45-16:00 Working on papers
  - Practical session bringing together elements from the course
- 16:00-17:00 Presentations and wrap-up

<!-- Ideas:
- Web app development
- Visualisation
- Getting your work out there
- Deciding which tools to use -->

## Alignment with Overarching Learning Outcomes

<!-- ### OLO 1: Entrepreneurship skills and competencies

> The capacity to identify, synthesize and act upon opportunities and ideas to create social, cultural and financial
value for others, including translating innovations into feasible business solutions, with sustainability at their
core, and to lead and support others in this process.

### OLO 2: Innovation skills and competencies

The ability to evaluate the research experiences combined with the knowledge, ideas and technology of
others to create, test and implement new or significantly improved products, services, processes, policies, new
business models or jobs, and to mobilize system innovation to contribute to broader societal change, while
evaluating the unintended consequences of innovation and technology.

### OLO 3: Creativity skills and competencies

The ability to extend boundaries and systematically explore and generate new ideas and to inspire and support others in this process and contribute to the further development of those ideas.

### OLO 4: Intercultural skills and competencies

The ability to engage and act internationally and to function effectively ‐ in research and other activities ‐ 
across cultures, sectors and/or organizations, to think and act appropriately and to communicate and work
with people from different cultural and organizational backgrounds.

### OLO 5: Making value judgments and sustainability competencies

The ability to identify short‐ and long‐term future consequences of plans and decisions from an integrated
scientific, ethical and intergenerational perspective and to merge this into their professional activities, moving
towards a sustainable and green society.


### OLO 6: Leadership skills and competencies

The ability of decision‐making and leadership based on a holistic understanding of the contributions of Higher Education, research and business to value creation. -->

The course will contribute to the development of the following skills and competencies:

- Entrepreneurship skills and competencies (OLO 1): The course will prepare researchers for working on real-world projects, up-skill their CVs to contain improved data science competencies, which are in high and growing demand in the job sector, and provide vital website development skills which are key to setting-up and running businesses in the digital age. The course will also provide insight into how academic research and papers can be implemented in practice, with reference to case studies such as the Propensity to Cycle Tool in which academic research was deployed in a national policy context, resulting in a tool that is now used by local authorities across England and Wales.

- Innovation skills and competencies (OLO 2): The course will provide participants test new products and tools, with a focus on new tools for data science, reproducible and scalable research, and a taster of web application development, that could be a game changer in the career path of students who have innovative ideas but currently lack the confidence or skills to implement them. There will be a focus on system innovation and contributing to broader positive societal change, with reference to the potential of open data and open source software to democratize access to data and tools for transport planning.

- Creativity skills and competencies (OLO 3): The course will encourage students to think outside the box, by providing opportunities on day 2 to apply the new tools taught in day 1 to a real-world problem of their choosing. The 'controlled chaos' session will provide a safe space for students to experiment with new tools and ideas, with the support of the course team and other participants.

- Leadership skills and competencies (OLO 6): The course will empower students with new tools and ideas that will enable them to take their research in new directions, for example by converting research methods into a new digital product. The 'can do' attitude advocated in the course will give students the confidence to take on new challenges and lead in their field, within and particularly outside of academia.